-
  name: Deploy a web application
  hosts: target1
  any_errors_fatal: true
  tasks:    
  #  - name: importar key Mesosphere
  #    shell: gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E56151BF

  #  - name: Add repo
   #   become: yes
    #  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu bionic main' state=absent

    - name: Install dependencies
      become: yes
      when: ansible_os_family == 'Debian'
      apt: 
        name: '{{item}}'
        state: present
        update_cache: yes
       # upgrade: yes
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python3-pip
        - python-mysqldb

    - name: Install MYSQL database
      become: yes
     # become_user: ubuntu
      apt: name={{ item }} state=present
      with_items:
       - mysql-server
       - mysql-client

    - name: Install PYMYSQL on DB Server
      become: yes
      pip:
        name: pymysql
        state: present

    - name: Start the MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create new database
      become: yes
      tags:
        - db
      mysql_db:
        name: '{{ db_name }}'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      #  check_implicit_admin: yes
       # login_user: '{{ db_user }}'
       # login_password: '{{ db_password }}'

    - name: Create New User
      tags:
        - user
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        priv: '*.*:ALL'
        host: '%'
        state: present
     #   login_unix_socket: /run/mysqld/mysqld.sock
    
    - name: Install Python Flask dependencies
      pip:
        name: '{{ item }}'
        state: present
      with_items:
       - flask
       - flask-mysql

    - name: Copy web-server code
      copy: src=app.py dest=/opt/app.py

    - name: Start web-application
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
