-
  name: Deploy a web application
  hosts: target1
  tasks:
    - name: Install dependencies
      apt: 
        name: '{{item}}'
        state: present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb